version: '3'
# Указывает версию формата docker-compose
# Версия 3 поддерживает большинство современных функций Docker

services:
  # Определяет сервисы, которые будут запущены
  app:
    # Название сервиса - "app"
    build: .
    # Указывает Docker собрать образ из текущей директории (где находится Dockerfile)
    
    volumes:
      # Определяет тома (volumes) для хранения данных между запусками контейнера
      - ./data:/dronetermsai/data
      # Монтирует локальную директорию ./data в /dronetermsai/data внутри контейнера
      # Это позволяет загружать файлы для обработки, помещая их в локальную папку data
      
      - ./results:/dronetermsai/results
      # Монтирует локальную директорию ./results в /dronetermsai/results внутри контейнера
      # Сохраняет результаты обработки (CSV, Excel файлы) в локальной системе
      
      - ./db:/dronetermsai/db
      # Монтирует локальную директорию ./db в /dronetermsai/db внутри контейнера
      # Сохраняет данные базы данных для персистентности между запусками
    
    tty: true
    # Выделяет псевдо-TTY, что необходимо для интерактивных приложений с консольным интерфейсом
    # Позволяет видеть вывод программы в реальном времени
    
    stdin_open: true
    # Держит STDIN открытым, что позволяет вводить команды в интерактивном режиме
    # Эквивалент флага -i в команде docker run


# Docker Compose упрощает запуск контейнеризованных приложений, особенно когда требуется настройка томов и других параметров. 
# Этот файл позволяет запустить приложение DroneTermsAI одной командой, обеспечивая сохранение всех данных между запусками.
# Запуск приложения: docker-compose up
# Остановка приложения: docker-compose down